theme: jekyll-theme-hacker
title: HeavisideSDR - Inexpensive Open-Source Digital HF
description: The HeavisideSDR project aims to build inexpensive digital HF transmitters and transceivers with remote capability with entirely open-source hardware, firmware, and supporting software.
